[#epistle_north_england, short="Epistle to Quakers in North England"]
== An Epistle to the people of God, called Quakers, in the north of England, to be read in all their meetings.

Beloved Friends, brethren and sisters, who are inhabitants of my native country,
whom the Lord, in the first breaking forth of his glorious gospel day,
in this latter age of the world, visited with the morning thereof,
the salutation of my endeared brotherly love flows forth, at this time,
to salute you all, with breathing desires to the Lord, for your preservation,
in the faith and fellowship of the gospel of peace; and that grace, mercy and truth,
with all the fruits of righteousness, may abound in and among you all,
that you may be a royal priesthood, and a holy nation; for God has called you thereunto,
that you might be made the first fruits to his praise;
for this end he called you out of darkness into his marvelous light.
This was the precious seed of his kingdom received by you,
by which Christ came to be manifest in male and female, the hope of our glory,
who is made a covenant of light to this northern Island of the Gentiles,
and who is to be God`'s salvation to the ends of the earth.

Of this inexpressible riches, I with you,
in the beginning of the breakings forth thereof,
received and were made partakers of the like precious faith, in which by a Divine hand,
I have been preserved to this day, through many tribulations.
All holy and living praises be given to the excellent name of our God forever,
who has not left us destitute of his mercies,
but has carried us by the right hand of his power, as on eagles`' wings,
through all difficulties, which hitherto he has allowed to be set before us;
so that we can say, our lot is fallen in a good land.

And now brethren, this I write unto you, that your joy may be full,
who keep the word of faith delivered unto you, and stand by faith, in covenant with God,
holding fast your confidence in him without wavering, who is the head of our body,
as living members fitly joined together in the bond of peace and love.

Here we are one another`'s joy in the Lord,
and fellow helpers in the work and service of the Lord in our day,
against Babylon the mother of harlots,
who has adulterated people`'s minds and hearts from God;
and thus has made the nations drunk with her wine,
under every green tree that has sprung up since her reign.
She has prevailed, but her judgment is begun, her torment prepared,
and the cup of indignation is determined of God for her;
for the hour of her judgment is come, and the executioner stands at the door.
Therefore all the servants of the Most High, whom the Lord has redeemed by his power,
from under the power of the beast, abide in him, who is now come for judgment,
that his holy city may be redeemed thereby;
for the Lamb`'s wife is returned out of the wilderness,
and is adorning herself with the white garments of praise for the spirit of heaviness,
which has, attended her in the long night of apostasy.
She is putting on her beautiful garments of righteousness,
and is nourishing her children with the sincere milk of the eternal word of life;
and they are grown strong in the Lamb`'s war,
to handle their spiritual weapons against the dragon and his power,
that has long reigned in the hearts of the sons and daughters of men.
They can no more war with flesh and blood,
but bend their bow against spiritual wickedness that has reigned in high places;
and this is the very nature and being of that spiritual life of the Son,
which the gospel day has brought to light.
Thus is the riches of the Gentiles brought, in the better hope and covenant,
than that which was made with Israel after the flesh,
which removed not the veil from their hearts, nor the curse from their tents;
but the Lord is come, who has taken away the veil which was over our hearts,
while Moses was read; this is the Lord`'s doing, by the finger of his right hand;
and it has had a marvelous effect in our day, to the gathering of many sons unto glory.
He has said unto the north, give up, and to the south keep not back;
and many have heard his voice, and are come forth of the graves of corruption,
and have put on the beautiful garments of righteousness,
and are walking in their ranks "`and order,
up to the holy mountain of the house of the Lord,
giving heed daily to the instruction of the Almighty, by his grace and Spirit,
who now teaches his people to profit, and guides the meek in judgment,
and gives wisdom and understanding to the simple soul, who has no helper in the earth;
all holy living praises ascend unto him from the living,
whom he has quickened forever more.

And now, dear Friends and brethren,
as the Lord has made you of the first fruits to his praise,
be all faithful and diligent servants and stewards in your Father`'s house,
and with girded loins attend upon your Lord`'s motion, word and call,
that you may be ready to answer him, in every service he has for you to do;
so shall you partake of the fulness and fatness of his house,
and he will give you your meat in due season, and fill your treasures,
that you may have wherewith to give to them who need.
Of this I am a witness, who came from amongst you in much poverty of spirit;
but the Lord filled my basket in all times of need,
so that I had bread to administer by him to the hungry,
and water to the thirsty traveller, and enough for myself besides;
and by faith it was renewed every day, and increased with using.
And now I can say, that I have been young, and am now grown old;
yet I never saw the righteous forsaken,
though I have often seen them cast down for a time,
yet has a Divine hand been under their head,
by which they have been supported under all exercises.

The Lord has not allowed any to be tempted beyond what he has given ability to bear,
as their faith has stood in his power, and the word of his patience kept to the end.
This I write unto you that your joy may be increased,
and that you may perfectly trust in the name of the Lord,
and go forth in the power of his might, to war with antichrist,
and the power of darkness, that reigns in the hearts of the children of disobedience.
For the weapons of our warfare are not carnal, neither do we war with flesh and blood,
but against that enemy that has separated men from God,
and to bring to the peaceable Savior,
who is now come to save men`'s lives from the destroyer.

In this peaceable life all live and walk, as you have had us for example;
that the Divine nature and property of the Truth,
may show itself forth in your lives and conduct, following peace with all men,
and holiness, without which none shall see God.
So shall your lives be pleasant, and your deaths peaceable,
though you may suffer reproach from men for a time.
Be not angry, or troubled at it, but count it your crown and joy in this life,
for the green196 tree endured greater sufferings, and thereby was made perfect;
"`and the servant is not greater than his Lord,`" nor more free than his Master,
from the woundings of the enemy; so with patience bear his yoke,
that with honor you may wear the crown.

The times and seasons are in the hand of the Lord,
and he disposes of the kingdoms of the world according to the good pleasure of his will,
and who shall say,
What are you doing? A sparrow shall not fall to the ground without his Divine providence.
Therefore, dear Friends,
trouble not yourselves about the transactions and mutations amongst men.
For all those things must be; the world is grown old in iniquity,
and the workers thereof must be cut off;
"`The mouth of the Lord of Hosts has spoken it.`" Touch not on the right nor
on the left with those dissensions that seem to infest the world,
for the wrath of man shall never work, nor bring forth the righteousness of God.
Neither shall wars with flesh and blood complete true and lasting peace on earth,
but righteousness shall deliver from death; the fruit thereof is peace,
and the effect thereof is quietness and assurance forever.
This is our interest, this is our all, the good old cause which Moses, Abraham,
and all the patriarchs, the true prophets and apostles labored for in their day,
through the several dispensations of grace and life,
in which God appeared to them--the end and tendency of all was to turn many to,
and bring forth the righteousness of God, which the world, by their wisdom, never knew,
nor does to this day.
And that religion is certainly false, which is either set up,
or defended by destroying men`'s lives.
Therefore touch not with it, but in the suffering seed of life let your dwellings be,
so shall you be fortified with the munition of rocks,
into which no destroyer shall enter.

And beware of, and watch against that evil seedsman,
who would sow division and contention among you.
Crush that in the bud wherever it appears;
and let all private interests give way to the public good,
peace and tranquillity of the church of Christ,
and let all strife and contention cease about words, names or things.
Every post and pillar which God has not raised up will fall,
though it is set by the Lord`'s post; and every plant which he has not planted,
will wither and decay, and come to nothing, before the glorious Sun that is now risen,
which only will nourish, comfort and refresh those plants which stand in the good ground.
For both the good and bad ground have received the seed of the kingdom of righteousness,
and marvel not that it has contrary effects;
for all the parables of the ancient gospel must be fulfilled.
And also all the promises to the royal chosen seed of God,
which brings forth righteousness in all mankind where it grows and prospers,
the yes and amen is witnessed; and the spiritual ministration of life,
is now to be spread over the whole earth,
which will fill it with the knowledge of the glory of God, as the waters cover the sea;
the last and greatest that ever the world shall be visited withal,
wherein God alone is known and worshipped, in and by his own Spirit,
by all who receive the manifestation thereof, given them to profit withal.
They alone shall know this heavenly treasure, in their earthen vessels,
that the excellency of the power may be of God, and the glory alone be given to him,
who alone is worthy forever.

Here all man`'s inventions, human traditions,
willings and runnings must be laid in the dust; and he must see himself lost,
and not able to move one step towards his eternal felicity, by all his acquired parts,
wisdom and abilities; so the Savior will manifest himself to him,
in order to his redemption.
For he is come to gather the lost sheep, scattered abroad in the nations,
who have no helper below him in the earth; but the whole need no physician,
who never knew a wounded spirit, nor a broken heart.
They do not know the Savior come to bind up such, nor to save them,
but to feed them with judgment, and to give the cup of indignation into their hand;
and he will take the cup of trembling out of the hands of his obedient children,
and give it into the hand of those who oppress them.
Therefore my beloved Friends, five in all holy subjection to the Truth,
and follow your Leader, Christ, fully and faithfully,
in that ancient path of righteousness which he has set before you.
So shall the angel of his presence go before you, and be to you a fountain in the way;
for all religion without righteousness, is but as chaff which the wind drives to and fro;
and in a storm into holes and corners;
and none can adorn the Truth further than he walks in the way of righteousness,
the ancient path of Abraham, Isaac and Jacob,
and all the true prophets and believers in the gospel day, towards their eternal rest.

And dear Friends and brethren,
inasmuch as God has caused his glorious gospel day to dawn in your hearts,
walk in the light of the Lamb,
that the salvation of God may be as a wall and bulwark about you;
and your sons may be as righteous plants, growing up in their youth;
and your daughters as polished stones, beautiful to behold,
being clothed with the garments of praise, the robes of righteousness,
then God himself will be their lover.
This will be the glory of our offspring,
and will crown their gray hairs with immortal honor,
if they continue faithful unto death,
and walk in the righteous footsteps of their ancestors;
being girded about with the Truth, and their lamps burning.

This is the preparation of the gospel of peace and reconciliation in our day,
testified unto in the mouths of many witnesses;
and many virgins are now trimming their lamps, and waiting for the Bridegroom,
that they may enter with him into his rest, who have come through many tribulations,
and have now put on their beautiful garments of praises, and hallelujahs,
being made white by the blood of the Lamb,
and have received the oil of joy for the spirit of heaviness.
But in this state let all be watchful, and rejoice with fear and trembling,
that a defence upon all your crowns may be witnessed;
for there is danger in the sabbath-day, as well as in the winter;
and none can be preserved, but as they abide within the munition of the Rock of ages.
For strength, help and preservation are in him,
who is arisen to fan the nations with the wind of his wrath,
who have drank the cup of fornication,
and all the chaff he will consume with the fire of his jealousy,
and waste the nations with his righteous judgments,
that he may "`gather the wheat into his garner,`" for the earth is filled with violence.

But the peaceable Savior is arising as a glorious Sun
to enlighten the earth with the knowledge of his glory;
and he will gather his sheep from the four corners thereof,
and bring judgment to the Gentiles,
for the recovery and redemption of Zion his beloved city.
Therefore you travellers,
who are coming up to the mountain of holiness where the Lord dwells; look not back,
nor downward to Sodom nor Egypt, out of which you are delivered;
nor have fellowship with the inhabitants thereof,
for they are the unfruitful workers of darkness;
but keep your holy fellowship and unity in the order of the gospel of peace,
in which is your strength, prosperity, growth and increase of life in him,
your holy Head, and in whom you have life, peace and rest forever.

And whatsoever has arisen,
or hitherto appeared to break or hinder our unity in the Spirit of life and Truth,
God has confounded, and it has withered as untimely figs;
and no weapon formed against us here, has or shall ever prosper;
for God will make his spiritual Jerusalem the praise of the whole earth.
"`Blessed are they who keep their habitations within the walls thereof.`"

And, dear Friends, though I have not outwardly seen your faces many years,
I would not have you therefore think that I am dead; for I bless the Lord,
I live by the faith of the Son of God, and my life is hid with Christ in God.
But consider, I have had many years the charge of a considerable family,
beyond many of my brethren, which the Truth engaged me to take care of;
and I have been in eleven prisons in this county, one of which held me ten years,
four months and upward, besides twice premunired, and once whipped,
and many other sufferings too long to relate here; but blessed be the Lord, my labor,
travels and sufferings have not been in vain,
for many have been thereby gathered to the true Shepherd`'s fold,
where they are laid down in rest and peace.
I could rejoice to see your faces,
but cannot bear to travel far by reason of my infirmity;
the harvest is great and the laborers are but few with us;
yet of late some young ones are raised up to be fellow helpers in the gospel testimony,
at which my soul rejoices.

I have lived to see the desire of my heart in measure answered,
and am thereby greatly satisfied,
and hope yet to see the beams of the glorious Sun of Righteousness arise and
break forth more and more in the hearts of the sons and daughters of men,
and the way of holiness opened to them, who yet sit in the solitary places of darkness;
this I long for more than my daily food.
For the earth can never enjoy her sabbaths again,
till the righteousness of faith is established in it;
and nothing short thereof can produce peace on earth and good will to men;
this the Lord has made us witnesses of in our day.
And that the glory and beauty of true Christianity can never
be restored to the nations and kingdoms of the world,
so much now lost and decayed, till they be turned to,
and live the life of righteousness and holiness;
then they will all see the God who made them.
This was the beauty of the ancient gospel Christians,
who were baptized into the death of Christ,
and so were made partakers of his resurrection.
This is the baptism that now saves all the true followers of the Lamb,
in the strait way of self denial.
Here the unclean cannot walk, nor the defiled enter;
it is only open and easy to the redeemed,
whose garments are washed in the blood of the Lamb,
being come through many and great tribulations.

Oh, Friends, walk in the gospel day, and "`love one another,
as God for Christ`'s sake has loved you;`" and let no rent or schism break in among you;
but let the seemless garment cover you all, that your nakedness may not appear to them,
who are without.
Your unity in the Spirit of Truth, is your strength,
which if you keep in the bond of peace, you shall do well.
For the great work and design of the adversary is, in this day,
to break in upon the heritage of God, and break their ranks;
but in vain is the snare laid for them, to whom God has given sight.

And now, dear Friends and brethren,
I once more salute you with the salutation of my endeared love,
which often flows towards you, and commend you to the grace of God,
which is sufficient to preserve you blameless until the coming of our Lord Jesus Christ,
to whom be glory, praise, power and dominion forever.
Amen.

I am your brother and fellow servant, in the labor of the gospel of peace,

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
Reigate, this 16th day of the Tenth month, 1692.
