[#letter_charles, short="Letter to Charles II"]
== A visitation of tender love from the Lord unto Charles II. King of England, Scotland and Ireland.

Let the consideration of these following lines deeply sink into your heart,
for they are things of great import to you at this day.
There is a people within your dominions, called Quakers,
whom the God of heaven highly esteems, in whose hearts he has placed his holy law,
according to his promise by the mouth of his prophets, which is, and has been,
their school master and leader unto Christ, according to the testimony of Paul,
his servant.
For their obedience to which law,
this people has undergone many great trials and tribulations,
both before and since your coming into this nation to rule as king,
which they have patiently borne, without avenging their own cause,
till the Lord did arise and plead with their enemies,
which he has done to their confusion '` and overthrow, even without remedy.
And this poor people were never known to provoke
the worst of their enemies to wrath against them,
unless by their honest conduct before them, coupled with God`'s fear and reverence,
which is of great price m his sight, though not valued in the sight of men;
for which they have suffered deaths often, long and sore imprisonments,
and great spoil of their goods, stoning, stocking, whipping and cruel mockings,
and much more, which is too tedious to mention,
for their due obedience to the royal law of God, and the weighty commands of Christ.
They have been denied the liberty of thieves and murderers, for their loyalty thereunto,
by them who were in authority before your coming in;
which God took occasion to destroy with remediless misery,
as a just reward of their ungodly deeds.
Then he remembered you,
whom he had suffered to be oppressed by the afore-named task-masters,
and did raise you from a low estate, in which estate when you wert low,
and in the sense thereof,
you promised much liberty to these harmless lambs of God`'s fold, saying,
they should not suffer for their religion, so long as they did live peaceably;
and much more, which may be seen abroad in public view.

Yet notwithstanding, their sufferings are much more increased under you, than before,
and you have broken your word and promises to them,
though they have kept faithful and true unto you,
and have not broken the peace of the kingdoms under you, nor any of your just laws,
but have labored by all lawful means to live a peaceable and quiet life under you,
in all godliness and honesty.
Yet how great is the cry of their oppression in this nation at this day,
from the one end thereof to the other? They are appointed as sheep for the slaughter,
even while they who work wickedness are set up in high estimation.
All which the righteous God has regarded, and his soul is greatly grieved every day;
and if these things be not speedily amended,
he will visit you and the whole nation in his hot displeasure; these,
and such like evils, were the overthrow of many great kings in the days of old,
whom when they forgot God and his cause, and oppressed and persecuted his people,
he did blast in their chiefest glory, and laid their honor in the dust.

So in all love and tenderness of heart consider what you have done, and are doing,
and remember your covenants with God and man in your low estate,
and let it be in no man`'s power further to charge you
with the breach of your word and promise.
Allow none to be oppressed for conscience sake in your dominions,
that do not disturb the peace of the kingdom,
as you will answer the contrary before the righteous God.
This can never be a good ingredient to to your future security with God or man,
neither will God ever bless you, or prosper your way in anything of this nature;
for his people is his portion which he has called and chosen,
and woe to all their enemies.
He that offends one of them,
it were better for him that a millstone were hanged about his neck,
and he cast into the midst of the sea.
And if any counsel you to vex and scourge the afore-named lambs,
such are your mortal enemies; and if you do hearken and obey them, it will bring shame,
reproach, confusion and desolation unto your crown and dignity.

Therefore be wise, O king, and recollect your memory while you have a day and time,
and consider your former engagements,
and also your father`'s and grandfather`'s charges laid upon you concerning these things,
and let love and mercy establish your throne, that your days may be prolonged.

Be not not high-minded or stouthearted against any;
that will never draw the hearts of your subjects to love you;
and so long as you allow the wicked to tread down the heritage of God,
you shall never have his countenance upon you,
but his displeasure shall attend you in your most secret chamber,
and at last he will give you up to be a prey to your enemies,
even as he has done many before, who rejected his counsel,
till his wrath sealed the truth of it in their bosoms.
Oh the cry of cruelty and oppression that is everywhere!
What will be the end thereof? None is now esteemed,
but such as can run greedily into iniquity, and drink it up as the ox drinks water.

The nations are in a flame, the fire of God`'s jealousy is kindled in every city and town,
even prepared to burn up all his enemies; and the iniquity of rulers, priests and people,
does blow it up day and night, that it cannot long be stayed,
unless it be speedily quenched by tears of unfeigned repentance;
for the hour of God`'s judgment approaches,
and the execution will speedily follow if not prevented.

This in short, I was moved to write unto you in true love,
who am and have been a sufferer under you for the testimony of Jesus; being no enemy,
nor never was to you,
that you may not run upon that which will be your final destruction;
but if you do reject the day of God`'s visitation in mercy to you,
he will take you off in his hot displeasure.
So the Lord open your eyes to see the things that belong to your peace,
before they be hid from you.

This was laid upon me once more to lay before you without flattering titles,
who am one of your suffering subjects, known by the name of

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
This was written the 2nd of the Seventh month, 1662.
