== To Friends in the Isle of Wight

Dear Friends,--Whom I often remember in the love of God the Father,
desiring at the throne of grace, that faith,
truth and love may be daily multiplied amongst you,
and that you may grow in the grace of God; from him which you have received,
and in the knowledge of his Son Christ Jesus, which you have obtained,
by the light of his glorious gospel that has shined in your hearts;
so that you need not say to your neighbor, or brother, know the Lord,
but from the least of you to the greatest,
is the saving knowledge of the mysteries of his
kingdom conveyed through the light of his Son.

As you walk in the light, your knowledge will increase,
and your fellowship with the Father and the Son, and one with another,
for the gospel fellowship stands in the light;
and now he who says he has fellowship with God and walks in darkness,
lies and does not the Truth.
Therefore keep your fellowship in the light and life of Jesus, your bishop, pastor,
and lawgiver, and walk by faith in him, so will his power go along with you,
to support you through all difficulties.
Be kindly affectioned one to another, and love one another,
as God for Christ`'s sake has loved you; and sit all down at the feet of Jesus,
that you may receive his wisdom and counsel, to guide you in all things,
so will you know the way of peace, which will lead you to your eternal rest.
And as God has shined in you by the light of his Son,
so let your light shine forth before men in works of righteousness,
by which saving faith is known, which works by love and obtains the victory.
The mystery of this faith is held in a pure conscience,
void of offense towards God and men; herein is your prosperity and safe standing.
And as you have received Christ, so walk in him,
all keeping your ranks and order in the body, eyeing your spiritual head,
who is given for your leader, governor and commander.
Dear Friends, meet often together, and wait at the heavenly altar;
and let your offering be a clean mind and heart, for that is the gospel offering,
and no offering without it has acceptance with God;
neither can any have access to God but by his Spirit, for it searches all things, yes,
the deep things of God; and tries all spirits that are gone out into the world,
putting a difference between the clean and unclean, the precious and the vile.
For many false prophets are abroad in the world, and have been many years, who cry,
lo here, and lo there is Christ, but go not out after them, nor believe them,
for the hope of true Christians is Christ within.
Col. 1:27, and they who are without this inward hope, they are without an anchor,
tossed like the waves of the sea with every wind of doctrine, through the sleight of men,
and cunning craftiness whereby they lie in wait to deceive.
Such are inwardly ravening wolves, and are everywhere known by their fruits;
but wait you, that Christ may be formed in you.
This is my travail and earnest desire for you, that you may be like minded,
having your loins girded with the Truth, waiting for the Bridegroom,
who is on his way to walk in his garden, that he has enclosed with the wall of salvation.
And now, dear Friends, I recommend you to the grace of God which is in you,
to be your continual teacher, that by it you may be saved, from the evil of this world;
and from the wrath to come.
My companion and I were in imminent danger of our lives by sea when we last left you,
going over in a little boat with a wicked pilot;
but the Lord brought us safe ashore about midnight, and gave us a calm passage,
without which we could not have continued: glory to his name forever.
And now I bid you all farewell,
hoping again to see your faces when the Lord opens my way;
to whose inward word I leave you to be guided in all things.
Amen.

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
Reigate. this 13th day of the Sixth month, 1691.
