[#to_all_friends_everywhere, short="To All Friends and Brethren Everywhere"]
== A general epistle to all Friends and brethren, everywhere; to be read among them in the fear of God.

My dearly beloved friends, brethren and sisters,
who are made partakers of that precious faith and word of it,
which was once delivered to the saints, and true gospel-believers and witnesses;
by and in which they were sanctified, justified and glorified.

My heart and soul do earnestly breathe to the Lord, that grace, mercy, truth and love,
may be daily increased, and abundantly multiplied, in and among you all;
and that you may be preserved a peculiar people, and royal priesthood,
daily increasing in fruits of righteousness,
as trees of the Lord`'s own right hand planting.
So shall his worthy name, by which you have been called, be glorified by you,
and his high praises be in your mouths, and a two-edged sword in your hands,
to wound the dragon and power of darkness, in all his appearances and transformings,
which are and have been many and various in our day;
so that some stars of heaven have been drawn down to the earth by his power,
and have made great noises at their fall.
But the foundation of God stands sure, and all who have continued upon it,
have been preserved unmovable, not only through all storms which have arisen in the sea,
but have escaped the baits and snares which have been laid covertly in the earth:
glory and renown ascend to that worthy name,
which has been our tower and safe habitation to this day; Amen, Amen forever.

And now, my dear friends, my life salutes you all, in the love of my heavenly Father,
which daily abounds and flows towards you, from the least to the greatest,
who retain your first love and integrity towards the Lord,
as witnesses for his name upon earth, in testimony and conduct.
You,
has the Lord chosen to be the first fruits to
the glory of his eternal and honorable name;
keep your vessels sound and clean, that He,
who is the fountain of all fulness and goodness, may daily fill your cups,
to hand forth to the thirsty, as he has filled ours, who went before you.

Oh! my dear brethren and sisters, abide in Him, your heavenly vine;
so shall every spring of life and virtue, that opens in and through you,
water those plants,
which the Lord by the right hand of his power has planted into his likeness,
that they might grow in grace, and in the knowledge of our Lord and Savior Jesus Christ,
and may be built up together in him a holy habitation, and spiritual household,
to dwell together in unity, as children of one Father:
so shall peace possess your habitations, and prosperity attend your undertakings.

This I have learned in my day, through many tribulations,
which have attended my pilgrimage in this world: in all which, I have been preserved,
by the mighty hand of God, through faith, to this day.

This I write for your encouragement, who are coming up in the same life and gift of God,
which he has ordained to open life, and the fountain of it,
to all nations and kindreds of the earth;
that his church may be restored to her ancient glory and beauty,
which have been eclipsed and marred,
in this long night of darkness and apostasy that has overspread the nations,
for many generations.
But now she is returning out of the wilderness, clothed with the sun;
and her lovers are gathering to her from many corners of the earth;
and her glory has eclipsed the wandering stars,
and will enrich the world with righteousness; so that peace on earth,
and good will to men,
shall be perfectly restored in all them who are made living members of her.
For so has Christ, her great prince, husband and lawgiver ordained,
that all her members should be holy and without blame before him,
as becomes his household and family.
So walk in him, and follow that path of life, and holy conduct,
which your feet have been turned into, by your ancients and elders;
many of whom are already gone to their rest, where the wicked cease to trouble,
and where the weary are at rest, and the voice of the oppressor is heard no more;
and the rest are following after, clothed with spiritual armor, the helmet of salvation,
and shield of faith;
by which we have all along been able to quench the fiery darts of the devil,
which have been many and great.

And you that are coming after, keep within your armor of light;
so shall the same power sustain you, and carry you, as on eagles wings,
through all difficulties which the Lord will yet permit to be set before you,
and will be your rock in the time of storm, and your shadow in the time of heat;
for he is become the rock of our age, as he was to ages and generations before us;
to all who have heard and obeyed his word, against whom no weapon hitherto has prospered.
For God will establish Zion, and build up Jerusalem of living stones,
upon the one foundation stone,
and many shall flock to her gates with songs of praise in their mouths:
for the gathering of the people shall be to Shiloh, the peaceable Savior,
that his kingdom of righteousness may be established again in the earth,
whereby she shall again enjoy her sabbaths.

For the Lord is arisen to awaken the nation,
and is putting trumpets in the mouths of many, to sound an alarm in his holy mountain;
and many are awakened, and rising out of beds of ease and carnal security,
where they have long laid polluted in their blood,
and are now putting off their night garments,
which have been stained and spotted with the flesh.
And He is now fitting many to be clothed with the
garment of praise for the spirit of heaviness,
that they may be called trees of righteousness, the planting of the Lord.
And many are made to run to and fro,
that divine knowledge and spiritual understanding of
the divine mysteries of God`'s eternal kingdom,
may again be restored; which have been long hid from the wise and prudent of this world,
but are now revealing and revealed to babes and sucklings;
out of whose mouths the Lord will perfect his praise and glory in the earth, which,
in due time, he will replenish with the knowledge of his glory, as the waters do the sea.

And now, my dearly beloved in the Lord, great and small, male and female,
my heart and soul daily breathe to the Lord for you all, in the bowels of Jesus Christ,
that you may walk worthy of that high and honorable calling, whereunto you are called,
in all humility and godly sincerity, as lights in the world;
so will you be daily baptized into the death of Christ,
and be made partakers of his resurrection; which none can have a part in,
but they who are first baptized into his death.
Such are arisen with him to newness of life,
and are earnestly seeking those things which are above; though they walk on earth,
yet their citizenship is in heaven, having an eye to the recompense of reward;
which no mortal eye has seen, nor can see, neither have entered into the heart of man,
the thing which God has prepared for them who love him: but he has revealed,
and is revealing them by his Spirit, to all who walk in it;
for the Spirit searches all things, yes, the deep things of God.

But believe not every spirit, but try the spirits, whether they be of God;
for some false spirits are already gone out, and have embraced this present world.
They went out from us, because they were not of us: for if they had been of us,
no "`doubt they would have continued with us;
their end will be answerable to their works.

But be you watchful and circumspect, whose eyes the Lord has opened,
that you may discern the enemy in all his cunning devices, both within and without;
and tried armor has been given you to resist him, if you keep it about you;
without which you cannot be safe from the jaws of him, who goes about as a roaring lion,
seeking continually whom he may devour.
Therefore dwell within that munition of rocks, with which you are surrounded,
and go no more forth; but keep your habitations in the light, where God dwells,
that you may enjoy his presence,
which will daily be an open fountain of life to your souls.
There your bread will be sure, and your water will never fail;
and the Lord will spread your tables in the midst of your enemies,
and bear up your heads through all difficulties.

This I have known, and many years experienced in my day;
by which I was abilitated to give my naked back to the rod of the wicked,
and my head to them who tore off my hair, and my body to bonds, and close confinement,
with other additional sufferings, which many years were my lot in the world;
in and through all which, the Lord carried me with cheerfulness and contentedness,
without the least murmuring.
But the longer I suffered, the easier it was made to me by the Lord.
I was freely given up to suffer all my days, as my enemies said I should; who said.
Aha, aha!
Thus we would have it. But the Lord disappointed them,
and set my feet at liberty over all their heads, when I least looked for it.

Glory, honor, and everlasting praises be to his honorable name forevermore;
who never fails them, whose dependence is upon him for preservation and deliverance.

And now my dear friends and brethren,
seeing this stormy winter is in a great measure over,
and the Lord in mercy has influenced the heart of this present government,
under which we live, to calmness and tenderness towards us:
let us be humbly thankful to him for it, and further engage the government,
by our peaceable behavior and deportment, in exercising ourselves,
and as much as in us lies, by all honest and lawful means,
to provoke others to the like acts of piety, justice and righteousness,
which will establish and exalt a nation, and be the greatest glory of the government.

Thus shall our thankfulness and service be manifested to them,
beyond all the flatteries of wicked and ungodly men,
among whom the government is not safe; for such were called, many ages ago,
the plague and pests of human society;
and entailed vengeance upon the places of their residence;
and the greatest enemies the government could have in their bowels.
For if righteousness exalts a nation, as the wise king said,
then unrighteousness must debase it, and bring contempt and reproach upon it.

So, dear friends, love the government under which God has placed us,
and seek the safety of it, by walking uprightly in it. And let prayers,
supplications and intercessions be made to God for all men,
especially for all who are in authority over us;
that under them we may live quiet and peaceable lives, in all godliness and honesty:
for this is good and acceptable in the sight of God our Savior,
who will have all men to be saved, and come to the knowledge of the Truth.

For our Savior is not come to destroy men`'s lives, but to save them;
not to influence his followers to be unfaithful to
whatsoever government he is pleased to set over them;
but on the contrary, to be subject to every ordinance of man for his sake;
being for the punishment of evil doers, and for the praise of them who do well.
To this end, purpose and intent, was government the ordinance of God.

And now, brethren, seeing the Lord has made us members of one body,
and of one household of faith, let us walk in love one towards another, and be content,
whatsoever station our great Father and Master has placed us in;
that he may delight to dwell with us, and give us our daily bread,
and nourish our souls with the milk of his word, up to eternal life:
this is our interest, this is our all;
that righteousness may be established in the earth, and in every house and family;
the fruits whereof are peace, and the effects thereof quietness and assurance forever.

So shall the true Christian sabbath be restored in the earth again, which has been lost,
in this long and dark night of apostasy,
which has been over the nations and families of the earth,
whereon the false church has sat as a queen, and seen no sorrow;
being decked on the outside with fine ornaments, pleasing to the fleshly eye,
whereby thousands have been enticed into her embraces,
because of the beauty and riches of her golden cup;
having not that eye opened which could see her inside,
as it is full of abomination and filthiness;
but the day and hour of her judgment is come, and more abundantly coming,
when the nations shall buy her merchandize no more;
for she has traded in slaves and souls of men, etc., Rev.
18.

But the day is sprung, which has discovered her skirts, and many see her nakedness,
and will trade with her no more.

The true church is returning out of her wilderness condition,
whose clothing is the Sun of righteousness, white as snow; she is travailing in pain,
for the deliverance of her sons and daughters
into the glorious liberty of the sons of God;
all changeable elements are under her feet: you that can read, may.
She is the true mother of all the faithful, and all her children are free,
walking in white linen, which is the saints righteousness;
and are inwardly adorned with the ornament of a quiet spirit,
which in the sight of God is of great price.
Her dwelling is within the munition of that rock,
which the gates of hell cannot prevail against.
The streets of her city are pleasant; in the midst of which is the river of life,
and all her flocks drink at it, which can never be drawn dry.

The bread of her city is of the finest of the wheat;
and her wine is well refined from the lees; which all partake of,
who dwell within her gates; and none can enter therein, who work abomination,
or love and make a lie, though her gates stand open by day.
Oh! you my dear friends, who are situated within her walls,
you have a sure and quiet habitation, out of the reach of the dragon`'s power:
keep your habitation, and walk in the light of the Lamb;
by which every trap and snare which the enemy lays in your way, will be seen,
and power given to escape.

Go forward in the name and power of the Lord,
and keep your station in the holy order of life, which God has placed you in;
and with zeal and fervency of spirit, keep your holy assemblies,
both first and week-days, that renewed acquaintance you may have with the Lord,
and the operation of his divine power;
through which we have been often renewed in the spirit of our minds,
and preserved through all storms that rose in the winter.

And now many being come to the sabbath day, there is as much need to watch,
and frequently to pray for the preserving hand of the
Lord of the sabbath to sustain and uphold us,
as ever.
For the crown is at the end of the race; which none can obtain,
but who continue to the end, in faith, patience, and well doing.

Oh! look not back at the glory of the world, and covet not the friendship of it,
which is enmity with God; and whosoever will be a friend of the world,
is an enemy of God.
But endure their hatred with a quiet mind, and have a special care it be for well doing;
and then their reproaches will be of more worth than all their treasures,
and as so many seals and witnesses of the day of your redemption:
for it is the suffering seed that must inherit glory and immortality with the Son,
when days in this world are ended.

And walk inoffensively among the sons and daughter`'s of men in all gravity and humility,
sobriety and temperance; that it may be known that you are taught by the grace of God,
and saved by its virtue and power, from the pollutions of the world,
and all the defilements of the flesh: for to this end did it appear unto you,
in an acceptable day.

And let young men and women have a care how they look out at the glory of the world,
where is the lust of the eye and the pride of life, which are not of God,
lest they be ensnared with them;
as were the young men of the Hebrews with the daughters of Moab,
which brought a plague upon Israel of old, by which twenty-four thousand fell.
These things were written for our learning, that we should not tempt God,
as some of them tempted him, and were destroyed.

And wait upon the Lord in faith and patience,
and he will give you whatsoever is needful for you, in his own due time;
and that with a blessing added.
This I have learned by long and good experience,
and recommend it to you as a brotherly caution,
not to seek lawful things by unlawful means; for that is not good in the sight of God.
But let the lamp of righteousness go before you, in all outward undertakings,
by which all snares which may be laid in the way, may be avoided,
and you preserved in the dominion of that life and power,
which subdues all things which are not of God.
And be not lifted up into high-mindedness, if the world`'s riches increase upon you;
for it is not always a sign of the favor of God.
And be not cast down when they are taken away;
for it is not always a sign of his displeasure, but may be for the trial of your faith,
patience and constancy in him, whose hand gives and takes away,
according to the good pleasure of his heavenly will;
unto which all his true-born children truly and patiently submit, and say,
"`Your will be done in earth, as it is done in heaven.`"

And walk in Him, your heavenly head, you who are elders, fathers and mothers of families,
as examples of gravity, temperance and modesty;
and be careful and watchful over your children, in their young and tender years;
and beware of letting them alone, without due and loving reproof,
for the least appearance of evil, in word or deed;
for so is the will of God concerning you,
to whom he has given power in their younger years,
to restrain every appearance of evil in them.
For they are of your loins, and you must be accountable for their evils, till they know,
and be made sensible of the Spirit of Truth in themselves; which,
when they come to the knowledge of, and by you are recommended thereunto,
if they turn aside therefrom, either to the right or left hand, you are so far clear,
and their miscarriages will lie at their own door; and their reward will be,
as those who know the Truth and do it not, to be beaten with many stripes.

There is a great obligation on parents,
to bring up their children in the nurture and admonition of the Lord,
the next to thankfulness for the gift of them; for they are blessings to parents,
when they grow up in the Tear and wisdom of God,
and a crown of rejoicing to their gray heirs.
This I know by experience:
glory to God on high! who has not left me destitute of his mercy in my old age,
and has given me to see, in a large measure, the travail of my soul in my young years.
He called me by his grace, near the first dawning of the gospel day in our age,
from my father`'s house,
and inclined my heart to inquire after and first
seek the kingdom of God and his righteousness,
with a promise to add all other things necessary.

This I have witnessed to be fulfilled to this day; having neither poverty nor riches,
but enough to sustain me, according to my soul`'s desire;
that I might not make my testimony for the Lord chargeable to any:
which has been fully answered to this day;
praises to his worthy and honorable name forevermore.

And you, brethren, who are called and chosen of God to minister his living word,
and made stewards in his house, of his manifold gifts; let your conduct in every respect,
be as becomes the gospel of peace; that it be not blamed, nor its glory eclipsed,
through any uncomely behavior, either in the sight of friends or enemies:
this will crown your ministry with many jewels.
And be not chargeable, or difficult,
nor more than needs be troublesome to them to whom you minister.
So shall your ministry have room in the hearts of many;
and you be instruments in the hand of our great Master, to turn many to righteousness;
having the promise of God for your reward, to shine as the stars forever and ever.

The consideration of this has overbalanced all my sufferings,
and made them sweet and pleasant to me, in my long pilgrimage in this world,
from the beginning.

And let none be lifted up with their gifts,
or appear in any lordliness over the flock and heritage of God; but in love, charity,
and brotherly kindness, you who are strong, bear the the infirmities of the weak;
considering that our great Lord bare all our infirmities,
and took upon him the form of a servant;
and his servants are not greater than their Lord.

My dear brethren, a word to the wise is enough: my brotherly love flows, as a fountain,
towards you all at this time; earnestly desiring,
that our ancient love and unity may be daily increased and renewed among us:
so shall we be firm and strong against all opposition,
both by the world and false brethren.

"`For, from among ourselves have men arisen, speaking perverse things,
to draw disciples after them;`" but they shall not proceed much further,
nor their weapons prosper;
but their folly shall appear to all whose eyes are kept single.

For God will prosper his work and spread his name in the earth;
and many shall yet come to behold the rising of the Sun of righteousness in their hearts;
for so shall the gospel day spring to all nations,
and the ministration of the spirit of life in Christ Jesus,
shall exceed in glory all that ever went before it,
and shall enrich the gentiles with righteousness,
and be the last and greatest that mankind shall be visited withal;
by which the knowledge of the power and glory of God, in due time, shall cover the earth,
as the waters do the sea.

Therefore, my beloved friends and brethren, press forward up to your holy city,
without fainting and weariness; and so run, that you may obtain:
and you will always find the Lord an open fountain in the way,
who will daily refresh your souls, and make you as a watered garden.
The Lord God of all our mercies be with us all,
and bless and prosper his work in our hands, to his eternal praise,
and our mutual joy and comfort forever.
With the renewed salutation of my true love to you all,
I am Your ancient friend and brother,

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
Reigate in Surrey, the 4th of the Fifth month, 1702.
