[#word_spirit, short="The Internal Word and Spirit of God"]
== A Treatise Concerning the Internal Word and Spirit of God.

In the beginning God made man upright, and gave him wisdom,
knowledge and understanding of life, fight and glory, in which, while he continued,
he delighted in the sight and presence of him who created him,
and gave him life and being.
Then he knew no evil, but the presence of God was with him,
and the tree of life planted for him, and he knew his Creator, God, who made him.
But of all the creation which hitherto the Lord had made,
there was not found a helpmate for him,
therefore the Lord caused a deep sleep to fall upon man,
and took one of his ribs and made woman.
They were both innocent in his sight,
till the serpent tempted the woman to break the covenant of life,
which God had made with them, by which they came to know evil,
and were deprived of the knowledge of life;
and death and darkness got dominion over them, being driven into the earth,
and made slaves to sin, and captives in the kingdom of darkness,
and therein ignorant of the chiefest good.
But it pleased the Lord, in infinite mercy,
to promise Christ under the name of the seed of the woman.
Gen. 3:15,
to redeem them from that slavery and bondage of
corruption into which they were fallen by transgression.
And because of the wickedness of men before the flood, the Lord said,
my spirit shall not always strive with man, for that he also is flesh: Gen. 6.
When the Lord gave to Israel his laws, adding the law upon them,
till the fulness of time was come, that the seed Christ was to be manifested;
he gave them also, with his statutes and judgments which he set before them,
his good spirit to instruct them, and give them knowledge of his mind and will,
Neh. 9:20, in all the statutes and judgments which the Lord then set before them.

While they obeyed and followed these,
they always had his divine secret upon their tabernacle,
and knew the angel of his presence to go before them in
all their undertakings for his name and glory,
and no enemy could stand before them, nor was any blessing with-held from them.
The Word and Spirit of God was very near unto them, even in their mouths and hearts,
that they might hear and do it, Duet. 30:14, and was the only guide of life,
and ground of obedience in all acceptable performances
to God in all ages and generations of the world,
and brought forth a ministration both of the law and prophets.

Jacob, by this spirit, prophesied of the coming of Christ,
long before the law was given by Moses:
Gen. 49:10. The scepter shall not depart
from Judah nor a law-giver from between his feet,
till Shiloh come, and the people shall be gathered unto him.
This was fulfilled in the coming of the Just One,
of whom all the prophets from Moses bore testimony: Acts 10:43.

Balaam became a great example of God`'s displeasure,
who erred from the spirit of the Lord, and loved the wages of unrighteousness,
though he dared not take it, nor could curse Israel;
but informed Balak of a way to ensnare their young men,
which brought a sore plague upon them, and kindled the wrath of God against Balaam,
that he became a sooth-sayer,
and was slain among the Midianites by the children of Israel,
according to the commandment of God: Josh. 13:22, Num. 31:8.

But while the children of Israel kept the word of the Lord,
and were instructed by his Spirit, in the time of Moses and Joshua,
and from Joshua to Judah, and in some of the prophets`' times,
their affairs both spiritual and temporal prospered,
and no enemy was able to stand before them.

By the Word and Spirit of God, Joseph interpreted Pharaoh`'s dream,
which none of the magicians could, Gen.
41, for which he was advanced to high dignity in Pharaoh`'s kingdom.

And Elihu said, I am full of matter,
the spirit within me compels me. Behold my belly is as wine which has no vent,
and as new bottles that break; therefore will I speak, that I may be eased,
I will open my lips and will answer: Job 32:18-20.

And David said, I have hid your word in my heart, that I might not sin against you:
Ps. 119:11. This word was a lantern unto his feet, and a light to his path,
verse 105. And he prayed God to direct his steps in it,
verse 133. O send out your light and your Truth; let them lead me,
let them bring me unto your holy hill, and to your tabernacles: Ps. 43:3.

But in Judah they set up prophets, but the word of the Lord was not in them,
and therefore they prophesied lies in the name of the Lord,
and he gave them up to be destroyed by the Chaldeans: Jer. 5.
For from the least of them to the greatest, every one was given to covetousness;
and from the prophet, even to the priest, every one dealt falsely.

But in all the righteous generations from the very creation,
in the several dispensations and ministrations in which they lived;
before the Scriptures were given forth,
the root and ground from which they performed their several services to God,
was the Word and Spirit of God.

Noah, by the word of the Lord before the flood,
was instructed to walk in the way of righteousness and pleased God,
and so was saved from the flood by the ark, for he was a preacher of righteousness:
Gen. 7:1; 2 Pet. 2:5.

And Abraham, by the Word and Spirit of God, received the covenant of circumcision, Gen.
17, and by the direction thereof left his father`'s house and his country,
and went into the land of Canaan, believing the promise of God,
that his seed should inherit it, though he had not so much in possession,
as to set his foot upon;
and offered up the son of his old age at the word and commandment of God,
of which by the Spirit of God he had perfect
knowledge before the Scriptures were given forth.

The prophet Isaiah said.
With my soul have I sought you in the night, yes, with my spirit within me,
will I seek you in the morning: Isa. 26:9.

And when the Lord restored Israel from among the heathen,
where he permitted them to be driven for their iniquities;
he promised to give them a new heart, and to put a new spirit within them,
and to cause them to walk in his statutes, and keep his judgments, and do them:
Ezek. 36:26-27, and 37:14.

And Daniel, the prophet, had the Spirit of the holy God, light,
wisdom and understanding in him, by which he interpreted the hand-writing on the wall,
that appeared before Belshazzar king of Babylon,
which all the wise men of Babylon could not understand, or interpret:
Dan. 5:11 and 6:3.

And in the gospel ministration,
the Spirit of Truth is universally tendered to all mankind,
to be the ground and cause of the true and saving knowledge of God,
and of his Son Jesus Christ, whom to know is eternal life: John 17:3.

And Paul testified to the Corinthians, as it is written, eye has not seen, nor ear heard,
neither have entered into the heart of man,
the things which God has prepared for them that love him.
But God has revealed them unto us by his Spirit, for the Spirit searches all things, yes,
the deep things of God:
1 Cor. 2:10-9. Here that great apostle gives pre-eminence to the Spirit of Truth,
beyond outward literature, though he had a great share of it, in searching all things,
yes, the deep things of God.
And Christ said to the Jews, all things are delivered unto me of my Father;
and no man knows the Son but the Father, neither knows any man the Father but the Son,
and he to whom the Son will reveal him:
Matt. 11:27. So the root and ground of the divine knowledge of God,
and the things of his kingdom, is by the revelation of the Son of God in man,
by his Spirit of grace, life and Truth, in the true gospel day.
The same gospel day having visited us, has brought, forth the same testimony,
so that whosoever attempts to search into the divine
mysteries of the deep things of God`'s kingdom,
and does not first receive the Spirit of Truth, and give up to be governed thereby,
and let it be the key in his hand and heart to open the door thereunto,
but climbs up and seeks to accomplish it some other way, is a thief and a robber,
and shall never find nor be able to unfold the secrets of the Lord,
which are only manifested to them who fear him:
Prov. 3:32. They are hid from the worldly wise and prudent,
that the more they increase in earthly knowledge,
the further they are from the depths of God`'s wisdom.

On this account, Christ said.
Strive to enter in at the strait gate, for many, I say unto you, will seek to enter in,
and shall not be able: Luke 13:24. But the spirit of man,
which is the candle of the Lord, being lighted by the Lord, searches the heart of man,
Prov. 20:27. Ps. 18:28,
and discovers the deceit and desperate wickedness thereof,
which none can know without it: Jer. 17:10-9. It manifests every evil thought,
word and deed, which the enemy of man`'s soul suggests to him,
and gives knowledge and understanding of the danger of it,
and in faith and patience waiting in it for strength to resist all evil,
it gives power and victory over it, so that none who loves the light,
and believes and walks in it, does complain for lack of power to resist the devil,
and all his assaults, temptations, and works of darkness.
But as many as thus receive Christ, the true light,
to them he gives power to become the sons and daughters of God, John 1:12,
and gives them the sight and knowledge of the door of entrance into his eternal kingdom,
and leads them by the right hand of his power thereunto; though strait is the gate,
and narrow is the way that leads to life, and few there be that find it;
for wide is the gate, and broad is the way that leads to destruction,
and many there be that go in thereat:
Matt. 7:13-14. So that whosoever gives not up to follow Christ,
the light of the world, can never enter in at the strait gate,
nor receive power to become the sons and daughters of God;
but are always complaining for lack of power to resist the devil,
and to do the will and work of God, which is man`'s sanctification.

Such have not yet received Christ as he is given of God, to be a Savior to ail mankind,
from sin and the power and prevalence of it; but count him a hard master,
who gives not sufficient power to do whatsoever he commands.

Such make him more unjust, as far as in them lies, than the evil one,
for he gives his servants full power to do his work, which is sin and iniquity;
so there is no complaint for lack of power to sin in thought, word and deed,
but his servants drink it in, as the ox drinks water, and commit sin with greediness,
without any complaint for lack of power to effect it.
Oh! beware of this unjust and blasphemous opinion,
or rather delusion of the wicked one, for it has led many to destruction,
by not improving of that talent which the great
Lord of heaven and earth has committed to them,
which is his Spirit, a manifestation thereof being given to every man to profit withal:
1 Cor. 12:7.

And though he seems now to have taken his journey into a far country,
yet he has delivered his goods to his servants, to every one talents,
according to his own pleasure, one at least to every one,
which at his coming he will require with advantage, i.e.,
the improvement of it in his absence; and who answers him herein shall have the sentence,
of "`Well done, good and faithful servant, enter you into the joy of your Lord.`"
But if any should neglect the improvement of this talent,
and hide it in his earthly heart, and say to his Master, when called to an account,
"`I knew you to be a hard man, who reaped where you sowed not,
and gathered where you scattered not, and I was afraid, and hid my talent in the earth,
behold you have your own,`" etc.: Matt. 25:21-25.

Oh! what was the dreadful sentence he received? You evil and slothful servant,
you ought to have improved my talent;
and he commanded it to be taken from him and given to him who had improved his talents,
and of five had made other five;
and yet more terrible! "`Cast the unprofitable servant into outer darkness,
where is weeping and gnashing of teeth forever:`"
verse 30. Oh! dread and fear the great God,
you who are sporting away your precious time, and eating, and drinking,
and rising up to play, and feasting, and rioting with gluttony,
and in words and hard speeches,
beating your fellow servants who are improving their
talents in the time given them of their great Master.

The manifestation of the Spirit is given to every man and woman to profit withal,
some after one manner, and some after another,
according to the divine wisdom of the Giver; some more, and some less, but a part to all,
which ought to be improved by all in their lifetime, and not resisted and quenched.
For this was the ruin of that great people the outward Jews, Acts 7:51,
and made them less sensible of the coming and power of Christ,
than were the unclean spirits, who confessed that they knew who the Son of God was,
saying, "`Let us alone, what have we to do with you,
you Jesus of Nazareth? Are you come to destroy us? I know you who you are,
the Holy One of God:`"

Mark 1:24. But the chief priests and scribes of the Jews knew him not,
but said he had a devil, John 7:20,
and also that he cast out devils by Beelzebub the prince of the devils:
Matt. 12:24. But if they had received the good Spirit of God,
which was given of the Father to instruct them,
they had by it known the power of his coming, and the virtue of his life,
which was given to ransom them and all mankind from darkness and the power of the grave.

This life was and is the light of men, John 1:4,
and enlightens every man that comes into the world,
verse 9. With and by this fight is the true and saving knowledge of God received,
2 Cor. 4:6, and by no other way or means whatsoever, for God is light, 1 John 1:5,
and manifests himself by and through his Son; and also whatsoever things are reproved,
are made manifest by the light, for whatsoever makes manifest the deeds of darkness,
is light, given of God to lead out of darkness, and the ways and works thereof:
Job 29:3, Isaiah 4:4. The light gives not only knowledge,
but direction to walk in the way of righteousness,
which alone leads to everlasting rest and peace with God:
Isaiah 32:17. Prov. 8:20. This is the way in which Abraham, Isaac,
and Jacob walked to their eternal rest, even the way of holiness,
which the unclean cannot walk in, but it is prepared for the wayfaring men, who,
though fools, shall not err therein.
No lion shall be there, nor ravenous beast shall walk therein, nor be found there;
but the redeemed shall walk there, and the ransomed of the Lord shall return,
and come to Zion with songs and everlasting joy upon their heads,
and sorrow and sighing shall flee away: Isaiah 35:8-10.

But as it happened to the outward Jews in their day,
who by resisting and quenching the measure of God`'s Spirit given them,
whereby they might have seen and known Christ,
in his appearing in that body of flesh in all things like unto man, sin excepted;
even so has it happened in our day, to the outward and nominal Christians,
who by resisting and quenching the Spirit of God given them,
are ignorant of the power and coming of our Lord Jesus Christ in spirit,
and cannot receive him, nor the testimony given of him by his servants,
but say as the mockers whom the apostle Peter warns the saints of,
who walked after their own lusts in the last days: These say,
Where is the promise of his coming? For since the fathers fell asleep,
all things have continued as they were.
Revelation is ceased, and nothing now to be depended upon, or expected,
but outward literature acquired by man`'s wisdom, and the letter of the Scriptures,
which the chief priests and scribes of the Jews had,
and thought to have eternal life in them, but would not come to Christ the light,
and so shut up the kingdom of heaven,
and all divine knowledge and under standing of
the things appertaining to the kingdom of God,
from the sons and daughters of men; and will neither enter themselves,
nor willingly allow those that would: Matt. 23:13.

But the root of divine knowledge is springing in many hearts,
and the true light is shining out of darkness in many souls,
to give the light of the knowledge of the glory of God in the face of Jesus Christ;
and this treasure we have in earthen vessels,
that the excellency of the power may be of God, and not of us: 2 Cor. 4:6-7.

And the ancient doctrine of our Lord and Savior Jesus Christ, is renewed again,
with living thanksgiving to God,
who has hid the secrets of his kingdom from the wise and prudent of the world,
and has revealed them by his Spirit, unto babes and children, who are taught of him;
and has chosen the foolish things of the world to confound the wise,
and the weak things of the world to confound the things which are mighty;
and base things of the world which are despised, has God chosen;
and things which are not, to bring to naught things that are;
that no flesh should glory in his presence.
This was the Lord`'s choice in the ancient gospel day: 1 Cor. 1:26-29.

Now this knowledge which is given to the weak and ignorant,
by the revelation of the Son of God in spirit, is saving, and gives life eternal,
to them who in faith and hope wait for it, and continue in it to the end;
and such can tell others what the Lord has done for their souls,
even what their hands have handled, and how they have tasted of the word of life,
and what their eyes have seen.
Such wait low at the feet of Jesus to hear his gracious words,
that they may speak what their ears have heard, and publish what their eyes have seen;
such gather not people to themselves, nor for their own gain and interest,
nor seek their own glory; but turn people to Christ,
the great shepherd and bishop of their souls, that they may hear his voice,
and follow him, that he may give unto them eternal life, according to his word:
John 10:27-28.

But the world`'s knowledge puffs men up into pride, mastership,
and lordship over God`'s heritage, and such are not examples of meekness,
humility and self-denial to the flock,
but like the scribes and pharisees which Christ cried woe against,
who loved the chief places at feasts, and to have the chief seats in the assemblies,
and greetings in the markets, and to be called of men rabbi, i.e. master: Mat.23:5,6.
Mark who these are in our day, and know them, not by their words, but fruits,
for that gives the true knowledge of them, to whom the woe now is, as Christ said:
Matt. 7:15-16. And they who increase in the world`'s knowledge, increase sorrow:
EcclEst. 1:18.

But he who would have true wisdom, and saving knowledge, must attain thereto,
by waiting and continuing in the fear of God, which is the beginning of it;
Prov. 9:10, and depart from pride, arrogance, and every evil way and work:
Prov. 8:13. This is the way to seal and confirm it to every soul;
true wisdom and knowledge cannot be gotten for gold, the price thereof is above rubies.
This little legacy I am willing to leave to the world,
which I have had long experience of, in my pilgrimage in this life,
that the root and ground of divine knowledge,
and spiritual understanding of the things of God`'s kingdom,
is near unto every man and woman, that they may go no more after them who say,
lo here is Christ, and lo there.
For many deceivers are, and for ages have gone out into the world,
who though in words they profess Christ`'s name,
and seem to have great veneration for him, yet in works deny him,
and will not that he shall rule in their hearts and consciences,
or be followed and obeyed in all things, calling him Lord and Master,
and yet do not his commandments.
These keep people learning all their days,
and yet the saving knowledge of the Truth is still hid from them,
and so freedom by it is never obtained, but such live under the bondage of corruption,
and die in their sins, for lack of receiving the word of the kingdom, the word of faith,
which is nigh in their hearts, and giving up to obey it. This Moses testified unto,
many ages and generations by-past, Duet. 30:14, saying to the house of Israel,
the word is very near unto you, even in your mouth and in your heart,
that you may do it. And David hid this word in his heart,
that he might not sin against God, Ps. 119:11, and it became a lantern to his feet,
and a light to his path: Ps. 119:105.

And all along in the true prophets`' days, the word of the Lord was in them, i, e. Christ,
whose name is called The Word of God, Rev. 19:13,
by which they prophesied of his coming into the world: Isa. 7:14,
Behold a virgin shall conceive and bear a son, and they shall call his name Emmanuel,
or God with us, which name can agree to none, but to him that is both God and man;
to which agrees the prophesy of the prophet Isaiah.
And the apostle, writing to the Romans concerning the righteousness of faith, etc.:
"`For Moses describes the righteousness which is of the law,
that the man which does those things shall live by them.
But the righteousness which is of faith speaks in this way: Say not in your heart.
Who shall ascend into heaven? (that is, to bring Christ down from above:) Or,
Who shall descend into the deep? (that is,
to bring up Christ again from the dead.) But what says it? The word is nigh you,
even in your mouth, and in your heart: that is, the word of faith, which we preach:
Rom. 10:5-8. John 8:31-32,`" by which freedom and redemption is obtained,
according to the testimony of Jesus Christ, when on earth.

And before he ascended to the Father,
he promised unto his disciples to send the Holy Ghost, which is the Spirit of Truth,
which should guide them into all truth: John 16:13. This was,
and is the true guide of life, doctrine, and conduct, to all true gospel believers,
and will so continue to the end, to all who truly receive it, and walk in it,
to whom there is no condemnation: Rom.
8:I. For the true gospel ministration is a ministration of the Spirit,
and its commands are spiritual, which no carnal man or woman, in that state,
can perceive or know; for they are spiritually discerned and received,
being included in the true and spiritual worship of God the Father,
in his Son Christ Jesus: John 4:23.

Therefore we say, with the apostle to the Ephesians,
who were grown up to the life and spirituality of Christianity, There is one body,
and one Spirit, even as you are called in one hope of your calling; one Lord, one faith,
one baptism, one God and Father of all, who is above all, and through all,
and in you all: Eph. 4:4-6.

And to the Colossians, when he instructed them concerning meats and drinks,
or in respect of a holy day, or new moon, or sabbath day; he said,
which all are a shadow of things to come; but the body is of Christ.
Wherefore, if you be dead with Christ from the rudiments of the world, why,
as though living in the world, are you subject to ordinances, (Touch not; taste not;
handle not;
which all are to perish with the using;) after the commandments and doctrines of
men? which things have indeed a show of wisdom in will worship and humility,
and neglecting the body etc., Col. 2:20-23.

Now they being come to the anti-type of all shadows, types and figures,
which were for a time allowed to be practiced in the first covenant,
though they did not disallow them in their time and place;
yet they witnessed an end of them, exhorting the saints to purge out the old leaven,
that you may be a new lump, as you are unleavened;
for Christ our passover is sacrificed for us: therefore, let us keep the feast,
not with old leaven, neither with the leaven of malice and wickedness,
but with the unleavened bread of sincerity and truth: 1 Cor. 5:7-8.

Here was that feast which ended, and was the substance of all the Jews`' feasts,
which were many and great,
in remembrance that the Lord passed over the doors of the Hebrews,
when he destroyed the Egyptians,
where the blood of the paschal lamb was sprinkled upon the lintel, and the door posts,
according to the commandment of Moses:
Ex. 12:22-23. And Christ the paschal lamb offered himself once for all,
that he might bear the sins of many,
in that body wherein he finished the work his Father gave him to do on earth,
which the Spirit of Truth, in our day, has given us the true knowledge,
and sincere esteem of; and also, that he is come again in Spirit,
to sprinkle our hearts with his blood; and if we keep within,
the destroying angel sent of God to smite the Egyptians, will pass over our houses.
This was typified by the outward passover, a feast often kept by the outward Jews,
who had the outward circumcision, temple and offerings; and yet were ignorant of Christ,
the true Christian passover,
whose blood had sprinkled the hearts and consciences of all true believers,
that the destroyer could not enter into their houses.
Thus was salvation brought about them, for walls and bulwarks,
according to the testimony of Isaiah the prophet:
Isa. 36:1. And the church began to put on her beautiful garments,
and no more to be called desolate or forsaken; for her stones were living,
built up together a spiritual household, a habitation of God, through his Spirit,
in which they worshipped him, and kept his ordinances; the true church,
her bread was living, and her wine well refined; her bishop and high priest was Christ;
her beauty was holiness, the beautiful garment, the Lamb`'s righteousness,
and crowned with glory and immortality.

This was her state in the ancient gospel day: but,
after the spirit of anti-christ prevailed, and men forsook the Lord,
the fountain of living waters, and hewed to themselves cisterns that would hold no water;
then the false church began to clothe herself with a glorious outside,
and sat as a queen, having a golden cup in her hand, full of filthiness;
so that she prevailed with the potentates of the earth, and made them drunk with her cup;
by which their hearts and minds were adulterated from God.
The great dragon, that old serpent, called the devil, being cast down into the earth;
the beast rose out of the sea, that had seven heads and ten horns,
and upon his heads the name of blasphemy.

And another beast rose out of the earth, which had two horns like a lamb;
but he spoke like the dragon, and exercised all the power of the first beast,
and caused them who dwelt on the earth to worship the beast, and to receive his mark,
both small and great, rich and poor, bond and free;
and deceived them that dwelt on the earth,
by the great wonders that he was permitted to work in the sight of the beast.

The dragon persecuted the true church, and cast a flood of water out of his mouth,
after the woman, that he might cause her to be carried away with the flood;
but the earth helped the woman, and opened her mouth, and swallowed up the flood.
Then was the dragon wroth with the woman, and made war with the remnant of her seed;
and the beast that arose out of the sea made war with them, and overcame them;
and power was given him, over every kindred, tongue and nation;
and all that dwelt upon the face of the earth worshipped him,
whose names were not written in the book of life of the Lamb,
which was slain from the foundation of the world.
Here darkness, and the power thereof, gained victory in the earth for many generations;
but a refuge for the true church was prepared in the wilderness,
where she was to be preserved, till the words of God were fulfilled,
and she has continued as a desolate widow for many generations.

But now she is returning, and putting on her beautiful garments, clothed with the sun,
and crowned with stars, which shine in the firmament of the Lord`'s power,
being mysteries of the heavenly Jerusalem, whose children are free,
begotten by the immortal word of life, and born of the immortal seed,
to be heirs of an incorruptible inheritance that fades not away;
and the eyes of many are opened, and yet will be opened, to see and behold her beauty;
for the Lamb is her husband, king and law-giver;
and the nations of them who are saved must walk in his light,
and the kings of the earth shall bring their glory and honor to it:
Rev. 21:23-24. The glory and honor of the Gentiles shall be brought unto it,
verse 26.

And whoever would attain to the true and saving knowledge of God,
and be saved from the wrath to come, must come to the light of the Lamb,
with which he has enlightened them, and walk in it,
which discovers the deceit of their hearts, and every evil thought, word and work,
before it is brought forth into action.
In it is power to resist the devil, in all his temptations and assaults;
and whoever believe in it, believe in Christ, and are children of God,
according to Christ`'s word: John 12:36, John 1:12. Rom. 8:14. For God is light,
and dwells in it, and the light dwells with him:
Dan. 2:22. Ps. 36:9 and 43:3 and 97:11 and 104:2 and 118:27.
Isa. 2:5 and 42:6 and 49:6 and 9:3. Micah. 7:8-9 Luke 2:32.
Acts 13:47. 1 Tim. 6:16. 1 John 1:5. This light is God`'s day,
every soul by it may see its Savior and deliverer, out of the bond of iniquity,
and house of darkness; in which, while men live and walk,
though the light shine never so clear, they cannot comprehend it, nor know the way of it,
nor understand the paths thereof, neither have any benefit by it,
in order to their salvation:
John 24:13. This is the light the apostle Peter
exhorted the gospel believers to take heed unto,
saying, we have a more sure word of prophecy,
(than that voice which was heard in the holy mount,) unto which you do well to take heed,
as unto a light that shines in a dark place, till the day dawn,
and the day star arise in your hearts;
2 Pet. 1:19. Here the gospel day was to spring, and the day star to appear,
in all true believers in the light, with which every one is enlightened,
that they may take heed to it; so shall the true gospel day dawn,
and the day star arise in their hearts, from generation to generation.

And blessed be the Lord, the gospel day now shines, and the darkness is past with many,
who are engaged to watch and be sober, having put on the breast-plate of righteousness,
and the shield of faith, and helmet of salvation, and the sword of the Spirit,
or spiritual sword, which is the word of God,
by which they are able to resist the enemy of their souls,
and to quench his fiery darts within and without.

The Lord is their shield and buckler, who trust in him, and depend upon his protection;
they never meet with disappointment from him, but always return victors; glory,
honor and living praises be unto his eternal and honorable name for evermore.

But many are ready to object and say, that false spirits and prophets are now come,
according to Christ`'s words to his disciples: Matt. 7:15,17,
Beware of false prophets, which come to you in sheep`'s clothing,
for inwardly they are ravening wolves: you shall know them by their fruits, etc.
Now let all seriously consider, that he spake to his disciples then in being,
many ages ago; that they should come to them,
and that by their fruits they should know them, i.e. the false prophets;
and the apostle John said to the little children in his day,
You have heard that antichrist shall come, even now are there many antichrists;
whereby we know it is the last time: they went out from us, for they were not of us:
1 John 2:18-19. And again in his 4th chapter.
Beloved, believe not every spirit, but try the spirits whether they be of God,
for many false prophets are gone out into the world: 1 John 4:1.

Christ had said, they should come, as above; and John said they were come,
and that they went out from them, because they were not of them,
else they would have continued with them.
I have declared above,
what bloody fruits they have brought forth in the world since they went into it;
which are obvious to every judicious eye, like briars and thorns,
of which no grapes can be gathered;
and have made the world as a wilderness full of wild beasts, and beasts of prey,
to this day.
Many false prophets are now in the world,
who through covetousness with feigned words are daily making merchandize of people,
such as the apostle Peter speaks of, 2 Pet. 2:1, but the day has discovered them;
glory to God on high, peace on earth, and good will to men.

Blessed be the Lord:
the Spirit of Truth is come which Christ promised that when he went to the Father,
he would send, John 16:7-14: I tell you the truth;
it is expedient for you that I go away; for if I go not away,
the Comforter will not come: but if I depart, I will send him;
and he described the fruits of the Spirit of Truth.
First, he should reprove the world of sin.
This every sinner on earth may witness to; that when he sins,
he is reproved within himself by the Spirit of Truth.
Secondly, he will reprove the world of righteousness and of judgment,
which every one who is in the world`'s righteousness may seal unto,
being but as filthy rags: Isa. 64:7.

This is that outside righteousness, which the scribes and pharisees had;
which Christ cried woe against: Matt. 23.
This righteousness the Spirit of Truth, now received by man, does reprove and judge,
being not the righteousness of faith which first cleanses the inside.
Thirdly, and when he is come, even the Spirit of Truth, he will lead you into all truth:
of this there are many witnesses at this day, who have received the Spirit of Truth,
and given up to walk in it; it has led them into all Truth, and out of all untruth.
Fourthly, he shall glorify me, for he shall take of mine, and show it unto you.
There are thousands can seal unto this, at this day,
who can and do glorify God in their bodies and spirits,
by virtue of that spirit they have received from him.
So we believe not every spirit, but try the spirits and prophets,
what fruits they bring forth, by the Spirit of Truth and the Holy Scriptures,
which we believe were given by divine inspiration; and are profitable for doctrine,
for correction, and for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished to every good work, 2 Tim. 3:16-17,
and do see and certainly know that those are false spirits and prophets,
who bring not forth fruits of holiness and righteousness in their lives and conduct.

Nor do they turn people to righteousness, or from the evil of their ways;
but keep them forever learning, that they may be ever paying,
and yet never savingly come to the knowledge of the Truth, whereby to be made free,
as Christ said to the Jews: John 8:31, If you continue in my word,
then are you my disciples indeed; and you shall know the Truth,
and the Truth shall make you free.
The Lord God open people`'s eyes,
that they may see and know the things that belong to their peace with God,
before it be hid from their eyes.

Amen.

This being the desire, and fervent prayer,
of him who would have all men come to the knowledge of the Truth, and be saved,
called among men,

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
Reigate in Surrey, the 8th of the Fifth month, 1703.
